//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public string ActivationCode { get; set; }
        public string Name { get; set; }
        public string Condition_value { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FailureTime { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
