//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<System.DateTime> RegistrationTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CounpId { get; set; }
        public Nullable<int> RemarkId { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual Remark Remark { get; set; }
        public virtual Customer_States Customer_States { get; set; }
    }
}
