//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArbitrarilyOrderEntities : DbContext
    {
        public ArbitrarilyOrderEntities()
            : base("name=ArbitrarilyOrderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Brand> Brands { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Coupon> Coupons { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Customer_States> Customer_States { get; set; }
        public DbSet<Packing> Packings { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Product_Status> Product_Status { get; set; }
        public DbSet<C_RecrivingAddress> C_RecrivingAddress { get; set; }
        public DbSet<Remark> Remarks { get; set; }
    }
}
